from prompts.templates import (
    CLASSIFY_PROMPT,
    SOLVE_COMPUTE_PROMPT,
    SOLVE_PROOF_PROMPT,
    SOLVE_CHOICE_PROMPT,
    SOLVE_GENERAL_PROMPT,
    VERIFY_PROMPT,
    REFLECTION_PROMPT,
    EXTRACT_ANSWER_PROMPT,
    SUBJECT_SPECIFIC_HINTS,
)

__all__ = [
    "CLASSIFY_PROMPT",
    "SOLVE_COMPUTE_PROMPT",
    "SOLVE_PROOF_PROMPT",
    "SOLVE_CHOICE_PROMPT",
    "SOLVE_GENERAL_PROMPT",
    "VERIFY_PROMPT",
    "REFLECTION_PROMPT",
    "EXTRACT_ANSWER_PROMPT",
    "SUBJECT_SPECIFIC_HINTS",
]
